# Jekyll Resume Theme

# Site settings
title: Tom Ridd Resume
email: 
description: This is a quick resume I have built to try out Jekyll for a project.
baseurl: ""
url: "http://thomasridd.github.io"
name: Tom Ridd
job: full stack engineer
location: London, UK
languages: data
twitter_username: thomasridd
github_username:  thomasridd
codepen_username:  
email_address: 

# Build settings
markdown: kramdown
